config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :products, only: :index

  resource :cart, only: [:show] do
    member do
      post 'add_to_cart'
      delete 'empty_cart'
    end
  end
  
  resources :carts, except: [:show] do
    member do
      delete :remove_from_cart
      post :add_quantity
      post :reduce_quantity
    end
  end

  resources :categories, onty: :show
  resources :orders, only: [:new, :index, :create]

  resources :products, only: [:index, :show]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products

  def sub_total
    sum = 0
    self.cart_products.each do |cart_product|
      sum+= cart_product.total_price
    end
    sum
  end

  def clear
    cart_products.destroy_all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart_products = current_cart.cart_products.includes(:product)
    @cart_sub_total = current_cart.sub_total
  end

  def add_to_cart
    chosen_product = Product.find(params[:product_id])
    if current_cart.products.include?(chosen_product)
      cart_product = current_cart.cart_products.find_by(product: chosen_product)
      cart_product.quantity += 1
      cart_product.save
    else
      current_cart.cart_products.create(product: chosen_product, quantity: 1)
    end

    flash[:success] = "Product added to the cart"
    redirect_back(fallback_location: products_path)
  end

  def remove_from_cart
    cart_product = current_cart.cart_products.find(params[:id])
    cart_product.destroy
    redirect_to cart_path(current_cart)
  end

  def add_quantity
    cart_product = current_cart.cart_products.find(params[:id])
    cart_product.quantity += 1
    cart_product.save
    redirect_to cart_path(current_cart)
  end
  
  def reduce_quantity
    cart_product = current_cart.cart_products.find(params[:id])
    cart_product.quantity -= 1
    cart_product.save
    if cart_product.quantity == 0 
      cart_product.destroy
    end

    redirect_to cart_path(current_cart)
  end

  def empty_cart
    current_cart.clear
    redirect_to root_path
  end
end

app/views/carts/_cart_product.html.erb
<div class="block-cart">
  <div class="block-img-product">
    <%= image_tag("new-product.png", alt: "Product")  %>
  </div>
  <div class="block-cart-product">
    <div class="mt-5 sm:mt-0">
      <h2 class="text-lg font-bold text-gray-900"><%= cart_product.product.name %></h2>
      <p class="mt-1 text-xs text-gray-700"><%= number_to_currency(cart_product.product.price, unit: "₴", format: "%n %u") %></p>
    </div>
    <div class="cart-product-button">
      <div class="flex items-center border-gray-100">
        <%= button_to '-', reduce_quantity_cart_path(cart_product.id), method: :post, class: 'button-cart rounded-l' %>
        <p class="px-2"><%= cart_product.quantity %></p>
        <%= button_to '+', add_quantity_cart_path(cart_product.id), method: :post,  class: 'button-cart rounded-r' %>
        <%= button_to "Remove", remove_from_cart_cart_path(cart_product), method: :delete, class: 'button-cart rounded  ml-1' %>
      </div>
      <p class="text-sm pt-6"><%= number_to_currency(cart_product.total_price, unit: "₴", format: "%n %u") %></p>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<div class="bg-gray-100 pt-20">
  <h2 class="title-cart">Cart</h2>
  <div class="block-products">
    <div class="rounded-lg md:w-2/3">
      <% @cart_products.each do |cart_product| %>
        <%= render 'cart_product', cart_product: cart_product %>
      <% end %>
    </div>
    <div class="block-global">
      <% @cart_products.each do |cart_product| %>
        <div class="block-global-info">
          <p><%= cart_product.product.name %></p>
          <p><%= cart_product.quantity %></p>
          <p><%= cart_product.total_price %></p>
        </div>
      <% end %>
      <hr class="my-4"/>
      <div class="flex justify-between">
        <p class="text-lg font-bold">Sum</p>
        <p class="mb-1 text-lg font-bold"><%= number_to_currency(@cart_sub_total, unit: "₴", format: "%n %u") %></p>
      </div>
        <%= link_to "Order", new_order_path, class: "button-order" %>
        <%= button_to 'Empty Cart', empty_cart_cart_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "button-order" %>
      </button>
    </div>
  </div>
</div>