config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :products, only: :index

  resource :cart, only: [:show] do
    member do
      post 'add_to_cart'
      delete 'empty_cart'
    end
  end
  
  resources :carts, except: [:show] do
    member do
      delete :remove_from_cart
      post :add_quantity
      post :reduce_quantity
    end
  end

  resources :categories, onty: :show
  resources :orders, only: [:new, :index, :create]

  resources :products, only: [:index, :show]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :cart_products
  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders, dependent: :destroy

  scope :by_category, -> (category) { where(category_id: category) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = category_resource
    @products = collection
  end
  
  private
  
  def category_resource
    Category.sort_position
  end

  def collection
    Product.all
  end
end

app/views/products/_product.html.erb
<section class="sectionn">
  <div class="flex font-sans">
    <div class="object-center w-3/12">
      <%= image_tag("new-product.png", alt: "Product")  %>
    </div>
    <form class="flex-auto p-6">
      <div class="flex flex-wrap">
        <h1 class="flex-auto text-lg font-semibold text-slate-900">
          <%= product.name %>
        </h1>
        <div class="text-lg font-semibold text-slate-500">
          <%= number_to_currency(product.price, unit: "₴", format: "%n %u") %>
        </div>
      </div>
      <div class="section-two">
        <div class="block-category">
          <%= product.category.name %>
        </div>
      </div>
      <p class="mb-10 text-sm text-slate-700">
        <%= product.description %>
      </p>
      <div class="flex space-x-я4 mb-6 text-sm font-medium">
        <div class="mr-10">
          <%= link_to 'Add to Cart', add_to_cart_cart_path(product_id: product.id), class:"link-to-cart", data: {turbo_method: :post} %>
        </div>
        <div>
          <%= link_to "Go to cart", cart_path(@current_cart), class:"link-to-cart" %>
        </div>
      </div>
    </form>
  </div>
</section>
<br/>

app/views/products/index.html.erb
<h2 class="title-category">All products</h2>
<div class="flex justify-center my-5">
  <% @categories.each do |category| %>
    <%= link_to category.name, category_path(category), class: "header-link-sign ml-10" %>
  <% end %>
</div>

<div>
  <% @products.each do |product| %>
    <%= render 'products/product', product: product %>
  <% end %>
</div>