config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :products, only: :index

  resource :cart, only: [:show] do
    member do
      post 'add_to_cart'
      delete 'empty_cart'
    end
  end
  
  resources :carts, except: [:show] do
    member do
      delete :remove_from_cart
      post :add_quantity
      post :reduce_quantity
    end
  end

  resources :categories, onty: :show
  resources :orders, only: [:new, :index, :create]

  resources :products, only: [:index, :show]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
end

app/views/layouts/_footer.html.erb
<footer class="block-cart-footer">
  <div class="mr-4">Тop for your money</div>
    <div  class="block-with-cart">
      <div class="flex items-center w-8 h-8">
        <%= link_to cart_path(@current_cart) do %>
          <%= image_tag "shopping-bag.png" %>
        <% end %>
      </div> 
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="inset-x-0 top-0">
  <nav class="container-nav">
    <div class="px-6 w-full flex flex-wrap items-center justify-between">
      <div class="flex items-center w-8 h-8">
        <%= image_tag("mitten.png", alt: "Mitten")  %>
      </div>
      <div class="px-10 navbar-collapse grow items-center">
        <ul class="header-unordered-list">
          <li class="link-page">
            <%= link_to "Home", root_path %>
          </li>
          <li class="link-page">
            <%= link_to "Products", products_path %>
          </li>
        </ul>
      </div>
      <div class="flex items-center lg:ml-auto">
        <% if user_signed_in? %>
          <%= link_to "#{current_user.first_name} #{current_user.last_name}", orders_path, class: "link-name" %>
          <%= button_to("LOG OUT", destroy_user_session_path, method: :delete, class: "header-link") %>
        <% else %>
          <%= link_to 'Log in', new_user_session_path, class: "header-link" %>
        <% end %>
          <%= link_to "Sing Up", new_user_registration_path, class: "header-link-sign" %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col h-screen justify-between">
    <%= render 'layouts/header' %>
    <% if flash[:success].present? %>
      <p><%= flash[:success] %></p>
    <% end %>
    <% if flash[:error].present? %>
      <p><%= flash[:error] %></p>
    <% end %>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>